# Allow to cache content generation.
cache:
  enable: true
# Remove unnecessary files after hexo generate.
minify: true

# Set the default view scheme
#scheme: Muse
#scheme: Mist
scheme: Pisces
# scheme: Gemini

# Light or Dark Mode
darkmode: true

# Enable or Disable Open Graph Protocol
open_graph:
  enable: true
  # Add pairs each line to customize
  options:
    type: blog
    title: Your Daily Tech Dose
    url: https://vasudev-gm.github.io
    site_name: Your Daily Tech Dose
    description: Latest tech news and analysis covering AMD, Apple, and emerging technologies
    image: /images/logo.svg
    fb_app_id:
    fb_admins:
    twitter_card: summary_large_image
    twitter_id:
    twitter_site:

# Menu entries
menu:
  home: / || fa fa-home
  about: /about/ || fa fa-user
  # tags: /tags/ || fa fa-tags
  archives: /archives/ || fa fa-archive
  Schedule Meeting: /schedule/ || fa fa-calendar
  sitemap: /sitemap.xml || fa fa-sitemap
#commonweal: /404/ || fa fa-heartbeat

menu_settings:
  icons: true
  badges: true

# Vanilla JavaScript plugin for lazyloading images.
lazyload: true

# Prefetch Critical Resources
preconnect: true
dns_prefetch:
  enable: true
  urls:
    - https://github.com
    - https://fonts.googleapis.com
    - https://fonts.gstatic.com

back2top:
  # Scroll percent label in b2t button.
  scrollpercent: true

# Better SEO
index_with_subtitle: true
exturl: true
exturl_icon: true

# Use Animate.css to animate everything.
# For more information: https://animate.style
motion:
  enable: true
  async: true
  transition:
    # All available Transition variants: https://theme-next.js.org/animate/
    menu_item: fadeInDown
    post_block: fadeIn
    post_header: fadeInDown
    post_body: zoomIn
    coll_header: fadeInLeft
    # Only for Pisces | Gemini.
    sidebar: fadeInLeft

# Follow me on GitHub banner in right-top corner.
github_banner:
  enable: true
  permalink: https://github.com/vasudev-gm

# Mobile Device Adaptation
mobile_layout_economy: true

# Enable FancyBox Plugin for displaying images, videos and more. Touch enabled, responsive and fully customizable.
fancybox: false  # Disable if not needed
mediumzoom: true # Lighter alternative to fancybox
