name: Pages

permissions:
  contents: read
  pages: write
  id-token: write

on:
  push:
    branches:
    # - main  # default branch
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        # If your repository depends on submodule, please see: https://github.com/actions/checkout
        submodules: recursive
    - name: Use Node.js 22
      uses: actions/setup-node@v4
      with:
        # Examples: 22, 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
        # Ref: https://github.com/actions/setup-node#supported-version-syntax
        node-version: '22'
    - name: Cache NPM dependencies
      uses: actions/cache@v4
      with:
        path: node_modules
        key: ${{ runner.OS }}-npm-cache
        restore-keys: |
          ${{ runner.OS }}-npm-cache
    - name: Install Dependencies
      run: npm install
      env:
        MSFT_CLARITY: ${{ secrets.MSFT_CLARITY }}
    - name: Require MSFT_CLARITY secret
      run: |
        if [ -z "$MSFT_CLARITY" ]; then
          echo "MSFT_CLARITY is not set. Aborting build to avoid deploying without telemetry secret." >&2
          exit 1
        fi
      env:
        MSFT_CLARITY: ${{ secrets.MSFT_CLARITY }}
    - name: Build
      run: npm run build
      env:
        MSFT_CLARITY: ${{ secrets.MSFT_CLARITY }}
    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ./public
  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
